### ISSUE TITLE
java.lang.IllegalArgumentException: Unsupported angle: -180

### ISSUE THREAD

**Issue by visro** [JeroenMols/LandscapeVideoCamera#19] opened 2016-04-02 16:10 UTC
java.lang.IllegalArgumentException: Unsupported angle: -180
    at android.media.MediaRecorder.setOrientationHint(MediaRecorder.java:419)
    at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.configureMediaRecorder(VideoRecorder.java:148)
    at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.initRecorder(VideoRecorder.java:122)
    at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.startRecording(VideoRecorder.java:87)
    at com.jmolsmobile.landscapevideocapture.recorder.VideoRecorder.toggleRecording(VideoRecorder.java:80)

**Comment by JeroenMols** [comment] 2016-04-21 18:43
@visro Any update on this? I cannot reproduce the issue locally.

**Comment by visro** [comment] 2016-04-23 15:27
I fixed the issue Unsupported angle: -180
Now i found new issue "No quality level found" in device with vga camera

**Comment by JeroenMols** [comment] 2016-04-23 15:38
Anything I can merge so others also benefit from the fix?

**Comment by JeroenMols** [comment] 2016-10-30 19:56
Closing as no follow up from reporter

**Closed by JeroenMols** 2016-10-30 19:56 UTC
